
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        5 Alasan Orang Memilih Obat Herbal | Bodrex     </title>
    <meta name="revisit-after" content="1 days" />
    <meta name="robots" content="index,follow" />
    <meta name="language" content="id" />
    <meta name="copyright" content="bodrex" />

    
				<meta name="description" content="5 Alasan Orang Memilih Obat Herbal - berikut ini adalah beberapa alasan mengapa popularitas obat herbal berhasil menembus zaman dan masih mejadi pilihan hingga sekarang." />
				<meta name="keywords" content="obat herbal" />
				<meta name="author" content="PT Tempo Scan Pacific Tbk" />
				<meta property="fb:admins" content="" />
				<meta property="fb:pages" content="" />
				<meta property="fb:app_id" content="464792840538630" />
				<meta property="og:title" content="5 Alasan Orang Memilih Obat Herbal" />
				<meta property="og:site_name" content="bodrex.com" />
				<meta property="og:url" content="https://www.bodrex.com/read/tips-dan-artikel/5-Alasan-Orang-Memilih-Obat-Herbal" />
				<meta property="og:description" content="5 Alasan Orang Memilih Obat Herbal - berikut ini adalah beberapa alasan mengapa popularitas obat herbal berhasil menembus zaman dan masih mejadi pilihan hingga sekarang." />
				<meta property="og:type" content="article" />
				<meta property="og:image" content="https://www.bodrex.com/files/5_Alasan_Orang_Memilih_Obat_Herbal.jpg" />

				<meta name="twitter:title" content="5 Alasan Orang Memilih Obat Herbal" />
				<meta name="twitter:description" content="5 Alasan Orang Memilih Obat Herbal - berikut ini adalah beberapa alasan mengapa popularitas obat herbal berhasil menembus zaman dan masih mejadi pilihan hingga sekarang." />
				<meta name="twitter:image" content="https://www.bodrex.com/files/5_Alasan_Orang_Memilih_Obat_Herbal.jpg" />
				<meta name="twitter:card" content="summary">
				<meta name="twitter:site" content="@keluargabodrex">
				<meta name="twitter:creator" content="@keluargabodrex">
				<meta name="twitter:domain" content="https://twitter.com/keluargabodrex">
				<meta name="google-site-verification" content="" />    <meta name="google-site-verification" content="W2R1n9upP_nxJ0I7shNtqTacpyUNk11Yv_XcJa8x2LY" />
	
	<link href="https://www.bodrex.com/read/tips-dan-artikel/5-Alasan-Orang-Memilih-Obat-Herbal" rel="canonical">
	
	<link rel="icon" type="image/png" href="https://www.bodrex.com/themes/front_site/images/favicon.png">	
	
	<link rel="preload" href="https://www.bodrex.com/themes/front_site/assets/fonts/Gotham-Black.otf" as="font" type="font/otf" crossorigin>
	<link rel="preload" href="https://www.bodrex.com/themes/front_site/assets/fonts/Gotham-Bold.otf" as="font" type="font/otf" crossorigin>
	<link rel="preload" href="https://www.bodrex.com/themes/front_site/assets/fonts/Gotham-Medium.otf" as="font" type="font/otf" crossorigin>
	<link rel="preload" href="https://www.bodrex.com/themes/front_site/assets/fonts/Gotham-Light.otf" as="font" type="font/otf" crossorigin>
	<link rel="preload" href="https://www.bodrex.com/themes/front_site/assets/fonts/Gotham-Book.otf" as="font" type="font/otf" crossorigin>
	<link rel="preload" href="https://www.bodrex.com/themes/front_site/assets/fonts/Gotham-Ultra.otf" as="font" type="font/otf" crossorigin>
	
    <link rel="stylesheet preload" as="style" onload="this.rel='stylesheet'" href="https://www.bodrex.com/themes/front_site/css/fonts.css">
    <link rel="stylesheet preload" as="style" onload="this.rel='stylesheet'" href="https://www.bodrex.com/themes/front_site/css/bootstrap.min.css">
    <link rel="stylesheet preload" as="style" onload="this.rel='stylesheet'" href="https://www.bodrex.com/themes/front_site/css/all.css">
    <link rel="stylesheet preload" as="style" onload="this.rel='stylesheet'" href="https://www.bodrex.com/themes/front_site/css/custom.css?ver=20210518062726">
    <link rel="stylesheet preload" as="style" onload="this.rel='stylesheet'" href="https://www.bodrex.com/themes/front_site/css/hamburger.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
		{
			"@context": "http://schema.org",
			"@type": "Organization",
			"address":{
				"addressLocality": "Tempo Scan Tower, 16th Floor",
				"addressRegion": "Jakarta",
			   "postalCode": "12950",
				"streetAddress": "Jl. HR. Rasuna Said Kav. 3-4"
			},
			"brand": "bodrex",
			"contactPoint": [{
				"@type": "ContactPoint",
				"telephone": "(021) 29218888",
				"contactType": "customer service"
			}],
			"logo": "https://www.bodrex.com/themes/front_site/assets/images/logo-bodrex-50th_rev1.png",
			"description": "bodrex dipercaya keluarga Indonesia cepat atasi sakit kepala, migrain, flu dan batuk.",
			"name": "bodrex",
			"URL": "https://www.bodrex.com/",
			"sameAs": [
				"https://www.facebook.com/bodrex","https://www.twitter.com/keluargabodrex", "https://www.instagram.com/bodrex","https://www.youtube.com/channel/UCSvekYyAlv6zCmxeWynElhg"
			]
		}
	</script>


    <!-- Facebook Pixel Code -->
    <script>
        ! function(f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function() {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1947639952152914');
        fbq('track', 'PageView');
        fbq('track', 'ViewContent');
    </script>
    <noscript>
	<img height="1" width="1" 
	src="https://www.facebook.com/tr?id=1947639952152914&ev=PageView
	&noscript=1"/>
	</noscript>
    <!-- End Facebook Pixel Code -->

</head>

<body>
	<div class="preloader">
		<div class="loading">
			<div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
		</div>
    </div>
    <main id="main">
                <div id="fb-root"></div>
        <script>
            (function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=464792840538630";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
                <header>
							<nav class="navbar fixed-top navbar-expand-lg navbar-header nav-fill navbar-standard">
								<div class="container">
						<a class="navbar-brand logo-navbar" href="https://www.bodrex.com/">
						<img src="https://www.bodrex.com/themes/front_site/assets/images/logo-bodrex-50th_rev1.png" alt="Bodrex" class="logo-brand">
					</a>
						<button class="navbar-toggler hamburger hamburger--spin" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</button>
						<!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button> -->
						<div class="collapse navbar-collapse justify-content-end" id="navbarText">
							<ul class="nav navbar-nav ml-auto">
								<li class="nav-item ">
									<a class="nav-link text-capitalize" href="https://www.bodrex.com/">
										<span>home</span>
										<!--span class="sr-only">(current)</span-->
									</a>
								</li>
								<li class="nav-item ">
									<a class="nav-link text-capitalize" href="https://www.bodrex.com/produk">
										<span>produk</span>
									</a>
								</li>
								<li class="nav-item ">
									<a class="nav-link text-capitalize" href="https://www.bodrex.com/tips-dan-artikel">
										<span>tips & artikel</span>
									</a>
								</li>
								<li class="nav-item ">
									<a class="nav-link" href="https://www.bodrex.com/tanya-bodrex">
										<span>#tanya<span class="text--bodrex">bodrex</span></span>
									</a>
								</li>
								<li class="nav-item ">
									<a class="nav-link text-capitalize" href="https://www.bodrex.com/store">
										<span>Beli Di Sini</span>
									</a>
								</li>
							</ul>
							<span class="navbar-text desktop-display ml-4">
							<a class="nav-link text-uppercase medium search-logo d-flex align-items-center justify-content-center"
								href="#" onclick="openNav()">
								<i class="fas fa-search"></i>
							</a>
						</span>
						</div>
					</div>
				</nav>
            <!-- Top Navbar Menu -->
        </header>
		<main class="page--content">
        <main class="artikel-read">
 <!-- Tanya bodrex button -->
<input type="hidden" id="url" value="https://www.bodrex.com/read/tips-dan-artikel/5-Alasan-Orang-Memilih-Obat-Herbal" />
<!-- Tanya bodrex button -->
<article class="isi-artikel">
	<div class="container">
		<section class="header">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="https://www.bodrex.com/">Home</a></li>
					<li class="breadcrumb-item"><a href="https://www.bodrex.com/tips-dan-artikel">Tips & Artikel</a></li>
					<li class="breadcrumb-item active" aria-current="page">
						5 Alasan Orang Memilih Obat Herbal					</li>
				</ol>
			</nav>
			<h1>
				5 Alasan Orang Memilih Obat Herbal			</h1>
			<label class="time-stamp">Selasa, 01 Januari 2019</label>
			<div class="gambar-artikel">
				
				<img src="https://www.bodrex.com/files/5_Alasan_Orang_Memilih_Obat_Herbal.jpg" class="gambar-artikel" alt="5 Alasan Orang Memilih Obat Herbal">
			</div>
		</section>
		<section class="isi-artikel">
			<p>Sejak dulu, obat tradisional atau disebut juga dengan <a href="https://www.bodrex.com/read/tips-dan-artikel/3-Alasan-Mengobati-Pusing-Sakit-Kepala-dengan-Obat-Herbal" title="3 Alasan Mengobati Pusing Sakit Kepala dengan Obat Herbal" target="_blank"><strong>obat herbal</strong></a>, telah dipercaya untuk mengobati berbagai penyakit. Beberapa waktu belakangan, banyak orang kembali memilih obat-obatan herbal untuk mengatasi masalah kesehatan mereka. Bukan tanpa sebab, berikut ini adalah beberapa alasan mengapa popularitas obat herbal berhasil menembus zaman dan masih mejadi pilihan hingga sekarang.</p><p><strong>Rekomendasi Orang Tua</strong></p><p>Banyak generasi muda tertarik untuk mencoba <a href="https://www.bodrex.com/read/tips-dan-artikel/Mungkinkah-Menghilangkan-Sakit-Kepala-dengan-Obat-Herbal" title="Mungkinkah Menghilangkan Sakit Kepala dengan Obat Herbal" target="_blank"><strong>obat herbal</strong></a> karena ada rekomendasi dari generasi sebelumnya, misalnya orang tua atau keluarga lainnya yang lebih tua. Pengalaman mereka menjadi sebuah referensi yang cukup dipercaya sehingga ada kecenderungan ingin mencoba dan membuktikan sendiri.</p><p><strong>Khasiat Teruji </strong></p><p>Khasiat <a href="https://www.bodrex.com/read/tips-dan-artikel/Seberapa-Ampuh-Menghilangkan-Sakit-Kepala-dengan-Obat-Herbal" title="Seberapa Ampuh Menghilangkan Sakit Kepala dengan Obat Herbal" target="_blank"><strong>obat herbal</strong></a> juga sudah dibuktikan. Masing-masing bahannya memiliki manfaat kesehatan, baik saat dikonsumsi secara terpisah maupun digabungkan. Misalnya saja jeruk nipis yang berkhasiat meredakan radang, madu untuk menekan batuk yang biasa kambuh pada suhu dingin , thymi yang dapat membantu mengeluarkan dahak, serta jahe yang bisa menghangatkan serta melegakan pada tenggorokan.</p><p><strong>Minim Efek Samping</strong></p><p>Obat herbal dibuat dari bahan-bahan rempah alami. Hal ini berbeda dengan obat non-herbal yang komposisinya mengandung zat kimia. Meskipun keduanya sama-sama dapat mengobati penyakit dan sudah teruji aman untuk dikonsumsi, namun bagi sebagian orang, obat herbal dianggap minim efek samping&nbsp; sehingga pengguna merasa lebih aman dan nyaman.</p><p><strong>Harga Terjangkau</strong></p><p>Secara umum, obat-obatan herbal memiliki harga yang lebih terjangkau. Hal ini dikarenakan bahan-bahannya berasal dari tanaman-tanaman yang mudah didapatkan di sekitar kita. Kemudahan mendapatkan bahan baku dan pengolahannya yang relatif lebih sederhana membuat harga <a href="https://www.bodrex.com/read/tips-dan-artikel/Mungkinkah-Menghilangkan-Sakit-Kepala-dengan-Obat-Herbal" title="Mungkinkah Menghilangkan Sakit Kepala dengan Obat Herbal" target="_blank"><strong>obat herbal</strong></a> relatif terjangkau.</p><p><strong>Praktis Dikonsumsi</strong></p><p>Kesan yang menunjukkan bahwa mengonsumsi <a href="https://www.bodrex.com/read/tips-dan-artikel/Seberapa-Ampuh-Menghilangkan-Sakit-Kepala-dengan-Obat-Herbal" title="Seberapa Ampuh Menghilangkan Sakit Kepala dengan Obat Herbal" target="_blank"><strong>obat herbal</strong></a> tidak praktis, rasanya sudah tak berlaku lagi. Saat ini obat-obatan herbal telah banyak diproses secara modern sehingga mendapatkan ekstrak dari bahan-bahan alami tersebut. Untuk mengobati batuk misalnya, Anda bisa mencoba <a href="https://www.bodrex.com/produk"><strong>bodrex Herbal Batuk</strong></a> yang mengandung kombinasi dari Madu, Thymi, Jahe, Akar kayu manis, Cabe Jawa, Kencur, Daun Sirih, Daun Sembung, Jeruk Nipis, Biji Pala, dan Peppermint oil. Kombinasi ini baik untuk meredakan batuk, melegakan tenggorokan dan bekerja tanpa ngantuk. Dikemas dalam bentuk <em>sachet</em>, menjadikan <strong>bodrex Herbal Batuk</strong> mudah dikonsumsi kapan dan dimana saja.</p>
		</section>
		<section class="share">
			
			<a id="fb-share" href="javascript:void(0); " class="btn button-share--facebook text-uppercase mr-3">
				<i class="fab fa-facebook-f mr-3"></i> share
			</a>
			
			<a rel="nofollow" href="https://twitter.com/intent/tweet?url=https://www.bodrex.com/read/tips-dan-artikel/5-Alasan-Orang-Memilih-Obat-Herbal&text=5 Alasan Orang Memilih Obat Herbal" class="btn button-share--twitter text-uppercase" target="_blank">
						<i class="fab fa-twitter mr-3"></i>tweet
					</a>			
		</section>
	</div>
</article>

	<section class="artikel-terkait">
		<div class="container">
			<h3 class="text-center text-uppercase py-4 produk-judul">
				ARTIKEL TERKAIT
			</h3>

			<div class="row row-cols-1 row-cols-md-4">
				<div id="824" class="col mb-4">
									<a href="https://www.bodrex.com/read/tips-dan-artikel/Wujud-Nyata-Peduli-Kemanusiaan-Tempo-Scan-Donasikan-Rp-500-Juta-untuk-Penanggulangan-Bencana-Alam-di-Kupang-NTT" role="button">
										<div class="card h-100 mb-4">
											<span class="badge badge-artikel">Berita</span>
											<img src="https://www.bodrex.com/thumb/Aksi-Peduli-Kemanusiaan-Tempo-Scan-di-Kupang-1.jpg" class="card-img-top" alt="Wujud Nyata Peduli Kemanusiaan, Tempo Scan Donasikan Rp 500 Juta untuk Penanggulangan Bencana Alam di Kupang, NTT">
											<div class="card-body">
												<h5 class="card-title">Wujud Nyata Peduli Kemanusiaan, Tempo Scan Donasikan Rp 500 Juta untuk Penanggulangan Bencana Alam di Kupang, NTT</h5>
												<p class="card-text">Tempo Scan Group memberikan bantuan sosial untuk masyarakat terdampak bencana alam di Kupang, NTT, dalam bentuk produk perawatan kesehatan, vitamin, ....</p>
											</div>
										</div>
									</a>
								</div><div id="823" class="col mb-4">
									<a href="https://www.bodrex.com/read/tips-dan-artikel/Aksi-Peduli-Kemanusiaan-Tempo-Scan-Donasikan-Rp-500-Juta-untuk-Penanggulangan-Bencana-Alam-di-Malang-Jawa-Timur" role="button">
										<div class="card h-100 mb-4">
											<span class="badge badge-artikel">Berita</span>
											<img src="https://www.bodrex.com/thumb/Aksi-Peduli-Kemanusiaan-Tempo-Scan.jpg" class="card-img-top" alt="Aksi Peduli Kemanusiaan, Tempo Scan Donasikan Rp 500 Juta untuk Penanggulangan Bencana Alam di Malang, Jawa Timur">
											<div class="card-body">
												<h5 class="card-title">Aksi Peduli Kemanusiaan, Tempo Scan Donasikan Rp 500 Juta untuk Penanggulangan Bencana Alam di Malang, Jawa Timur</h5>
												<p class="card-text">Tempo Scan Group memberikan bantuan sosial untuk masyarakat korban bencana alam di Malang, Jawa Timur dalam bentuk produk perawatan kesehatan, ....</p>
											</div>
										</div>
									</a>
								</div><div id="821" class="col mb-4">
									<a href="https://www.bodrex.com/read/tips-dan-artikel/Sering-Sakit-Kepala-Tegang-karena-Butuh-Liburan-Cobain-5-Ide-Liburan-Di-Rumah-Aja" role="button">
										<div class="card h-100 mb-4">
											<span class="badge badge-artikel">Sakit Kepala</span>
											<img src="https://www.bodrex.com/thumb/Sering_Sakit_Kepala_Tegang_karena_Butuh_Liburan.jpg" class="card-img-top" alt="Sering Sakit Kepala Tegang karena Butuh Liburan? Cobain 5 Ide Liburan Di Rumah Aja">
											<div class="card-body">
												<h5 class="card-title">Sering Sakit Kepala Tegang karena Butuh Liburan? Cobain 5 Ide Liburan Di Rumah Aja</h5>
												<p class="card-text">Meski tidak mudah, ada baiknya Anda tetap menunda dulu rencana liburan dan bepergian. Sebagai gantinya, jika Anda sering sakit kepala ....</p>
											</div>
										</div>
									</a>
								</div><div id="820" class="col mb-4">
									<a href="https://www.bodrex.com/read/tips-dan-artikel/bodrex-Merah-Putih-Berbagi-Kembali-Beraksi-Mendukung-Pendidikan-Indonesia-di-Masa-Pandemi" role="button">
										<div class="card h-100 mb-4">
											<span class="badge badge-artikel">Berita</span>
											<img src="https://www.bodrex.com/thumb/Visual-Artikel-BMPB.jpg" class="card-img-top" alt="bodrex Merah Putih Berbagi Kembali Beraksi Mendukung Pendidikan Indonesia di Masa Pandemi">
											<div class="card-body">
												<h5 class="card-title">bodrex Merah Putih Berbagi Kembali Beraksi Mendukung Pendidikan Indonesia di Masa Pandemi</h5>
												<p class="card-text">Tak hanya sektor bisnis, masa pandemi juga memberikan dampak yang cukup signifikan bagi sektor pendidikan Indonesia yang membuat ditiadakannya proses ....</p>
											</div>
										</div>
									</a>
								</div>				
			</div>
		</div>

	</section>
</main>
        			<div class="tanya-bodrex">
				<a href="https://www.bodrex.com/tanya-bodrex">
					<img src="https://www.bodrex.com/themes/front_site/assets/images/tanya-bodrex.png" alt="tanya-bodrex" class="widget-tanya-bodrex">
				</a>
			</div>
        		</main>
        <footer>
            <div class="d-flex flex-row justify-content-center top-footer">
                <a href="https://www.twitter.com/keluargabodrex" target="_blank" rel="noopener">
                    <div class="icon-frame-footer">
                        <i class="fab fa-twitter icon-footer"></i>
                    </div>
                </a>
                <a href="https://www.youtube.com/channel/UCSvekYyAlv6zCmxeWynElhg" target="_blank" rel="noopener">
                    <div class="icon-frame-footer">
                        <i class="fab fa-youtube icon-footer"></i>
                    </div>
                </a>
                <a href="https://www.facebook.com/bodrex" target="_blank" rel="noopener">
                    <div class="icon-frame-footer">
                        <i class="fab fa-facebook-f icon-footer-facebook"></i>
                    </div>
                </a>
                <a href="https://www.instagram.com/bodrex"  target="_blank" rel="noopener">
                    <div class="icon-frame-footer">
                        <i class="fab fa-instagram icon-footer"></i>
                    </div>
                </a>
            </div>
            <nav class="bottom-footer background-bottom-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-1 text-center text-sm-left">
                            <div class="bottom-footer-link">
                                <a href="https://www.bodrex.com/">
                                Home
                            </a>
                            </div>
                        </div>
                        <div class="col-sm-1 text-center text-sm-left">
                            <div class="bottom-footer-link">
                                <a href="https://www.bodrex.com/produk">
                                    Produk
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-2 text-center text-sm-left">
                            <div class="bottom-footer-link">
                                <a href="https://www.bodrex.com/tips-dan-artikel">
                                    Tips & Artikel
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-2 text-center text-sm-left">
                            <div class="bottom-footer-link">
                                <a href="https://www.bodrex.com/tanya-bodrex">
                                    <span>#tanya<span class="text--bodrex">bodrex</span></span>
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-2 text-center text-sm-left">
                            <div class="bottom-footer-link">
                                <a href="https://www.bodrex.com/store">
                                    Beli Di Sini
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-4 mt-5 mt-sm-auto text-center text-sm-right ">
                            <h3 class="text-uppercase temposcan-peduli">tempo PEDULI KONSUMEN</h3>
                            <h3 class="kontak"><i class="fas fa-headset"></i> 0800 150 8888</h3>
                            <p class="text-capitalize waktu-aktif">senin - jumat : 09.00 - 17.00</p>
                        </div>
                    </div>
                </div>
            </nav>
			<div class="d-flex flex-row justify-content-center top-footer copyright">
                <p style="color: white; margin:auto; padding: 10px 0"">
                    © 2021 bodrex. All rights reserved.
                </p>
            </div>
        </footer>

        <div id="mySidenav" class="sidenav">
            <button id="btn-search-close" class="btn closebtn" aria-label="Close search form" onclick="closeNav()">
                <img src="https://www.bodrex.com/themes/front_site/images/icon-search-close.png" alt="close">
            </button>
            <form class="search__form" method="get" action="https://www.bodrex.com/post/search">
                <input class="form-control search__input" name="q" type="search" placeholder="Cari kata kunci..." autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">
            </form>
            
        </div>
    </main>
    <script>
        function openNav() {
            var open = document.getElementById("main");
            document.getElementById("mySidenav").style.width = "100%";
            open.classList.add("main-search")
        }

        function closeNav() {
            var close = document.getElementById("main");
            document.getElementById("mySidenav").style.width = "0";
            close.classList.remove("main-search")
        }
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://www.bodrex.com/themes/front_site/js/bootstrap.bundle.min.js"></script>

    <script>
        $(window).scroll(function() {
            var scroll = $(window).scrollTop();
            if (scroll > 10) {
                $(".navbar-header").css("background", "var(--secondary-color)");
                // $("li.nav-item span").css("color", "white");
                // $("li.nav-item.active span").css("border-bottom", "2px solid white");
                $("li.nav-item span").addClass("scrolled");
                $("li.nav-item.active span").addClass("scrolled");
            } else {
                $(".navbar-header").css("background", "transparent");
                // $("li.nav-item span").css("color", "var(--secondary-color)");
                // $("li.nav-item.active span").css("border-bottom", "2px solid var(--secondary-color)");
                $("li.nav-item span").removeClass("scrolled");
                $("li.nav-item.active span").removeClass("scrolled");
            }
        })
		jQuery(
		  function($) {
			 var footer = $('footer'),
				btnTop = $('.tanya-bodrex');
			  
			$(window).scroll(function() {

                if ((btnTop.offset().top + btnTop.height()) >= (footer.offset().top - 10)) {
                    btnTop.addClass('tanya-bodrex--bottom');
                };

                if (($(document).scrollTop() + window.innerHeight) < (footer.offset().top)) {
                    btnTop.removeClass('tanya-bodrex--bottom');
                };
            });
		  }
		);
    </script>

    <script>
        var $hamburger = $(".hamburger");
        $hamburger.on("click", function(e) {
            $hamburger.toggleClass("is-active");
            // Do something else, like open/close menu
        });
    </script>

    <script>
        var $base_url = 'https://www.bodrex.com/';
		
				
				
        $('.load-more').click(function() {
            $(this).hide();
            var id = $('.item:last').attr('id');
            $.ajax({
                url: $base_url + "home/load_more/" + $("#kategori").val() + '/' + id,
            }).done(function(html) {
                $("#article-list").append(html);
                $('.load-more').show();
            });


        });

        $("#load-pertanyaan").click(function() {
            $(this).hide();
            var id = $('.item-pertanyaan:last').attr('id');
            $.ajax({
                url: $base_url + "tanyabodrex/load_more/" + id,
            }).done(function(html) {

                $("#q-box").append(html);
                $("#load-pertanyaan").show();
            });
        });

        $(".submit").click(function() {
            //$("#question-form input").css('border', 'none')
            var params = $("#question-form").serialize();
            $.ajax({
                type: 'POST',
                url: $base_url + "tanyabodrex/submit_question/",
                data: params,
                dataType: 'json',
                async: false,
                success: function(datax) {
                    if (datax.status == 1) {
                        $("#question-form input").val('');
                        $("#question-form textarea").val('');
                        $(".alert-success").show();
                    } else if (datax.status == 2) {
                        $(".alert-warning").show();
                    } else {
                        $(".alert-danger").show();
                    }
                },
                error: function(x) {
                    console.log("Error: " + "\r\n\r\n" + x.responseText);
                }
            });


            return false;
        });

        $("#fb-share").click(function() {
            FB.ui({
                method: 'share',
                href: $("#url").val(),
            }, function(response) {});
            /* FB.ui({
            	  method: 'feed',
            	  name: $("#title").val(),
            	  caption: 'bodrex',
            	  description: $("#short_description").val(),
            	  link: $("#url").val(),
            	  picture: base_url+'files/'+$("#file_name").val(),
            	}, function(response){
            		
            	
            	});  
            return false; */
        });
		
		/* function closeWin()   // Tested Code
		{
		var someIframe = window.parent.document.getElementById('iframe_callback');
		someIframe.parentNode.removeChild(window.parent.document.getElementById('iframe_callback'));
		} */
		
		
		function init() {
			var youtube_video_iframe = `
			<div id="modal-video" class="modal modal-std fade" tabindex="-1" role="dialog" aria-labelledby="modalVideo" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<img src="https://www.bodrex.com/themes/front_site/images/icon-search-close.png" alt="">
							</button>
						</div>
						<div class="modal-body nopadding">
							<div class="embed-responsive embed-responsive-16by9">
								<iframe id="iframe_callback" width="560" height="315" data-src="https://www.youtube.com/embed/nMLW3-RkcQA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
							</div>
						</div>
					</div>
				</div>
			</div>`;
			$('.youtube_video_iframe').append(youtube_video_iframe);
			var vidDefer = document.getElementsByTagName('iframe');
			for (var i=0; i<vidDefer.length; i++) {
			if(vidDefer[i].getAttribute('data-src')) {
			vidDefer[i].setAttribute('src',vidDefer[i].getAttribute('data-src'));
		} } 
		
		$("#modal-video").on('hidden.bs.modal', function (e) {
			$("#modal-video iframe").attr("src", $("#modal-video iframe").attr("src"));
		});
		
		}
		
		
		function banner() {
		var imgDefer = document.getElementsByTagName('img');
		for (var i=0; i<imgDefer.length; i++) {
		if(imgDefer[i].getAttribute('data-src')) {
		imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src'));
		} } }
		window.onload = banner;
    </script>
	
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-46299324-1', 'auto');
	  ga('send', 'pageview');

	</script>
	
</body>

</html>
